---
- name: "{{ 'Check if ' + item + 'is enabled' }}"
  ansible.builtin.stat:
    path: "{{ '/etc/apache2/mods-enabled/' + item + '.load' }}"
  register: statresult
  become: "{{ lihas_become | default(no) }}"
- name: "Apache2: disable module {{ item }}"
  ansible.builtin.command: a2dismod {{ item }}
  notify: restart_apache2
  changed_when: true
  when: statresult.stat.exists
  become: "{{ lihas_become | default(no) }}"
