---
- name: "{{ 'Check if ' + item + ' is enabled' }}"
  ansible.builtin.stat:
    path: /etc/apache2/conf-enabled/{{ item }}.conf
  register: statresult
  become: "{{ lihas_become | default(no) }}"
- name: "{{ 'Check if ' + item + ' is available' }}"
  ansible.builtin.stat:
    path: /etc/apache2/conf-available/{{ item }}.conf
  register: statresultavail
  become: "{{ lihas_become | default(no) }}"
- name: "Apache2: enable conf {{ item }}"
  ansible.builtin.command: a2enconf {{ item }}
  notify: reload_apache2
  changed_when: true
  when: '(not statresult.stat.exists ) and ( statresultavail.stat.exists )'
  become: "{{ lihas_become | default(no) }}"
