---
- name: check if {{ item }} is enabled
  ansible.builtin.stat:
    path: /etc/apache2/mods-enabled/{{ item }}.load
  register: statresult
  become: "{{ lihas_become | default(no) }}"
- name: "apache2: disable module {{ item }}"
  ansible.builtin.command: a2dismod {{ item }}
  notify: restart_apache2
  when: statresult.stat.exists
  become: "{{ lihas_become | default(no) }}"
