---
- name: "{{ 'Check if ' + item + ' is enabled' }}"
  ansible.builtin.stat:
    path: "{{ '/etc/apache2/sites-enabled/' + item + '.conf' }}"
  register: statresult
  become: "{{ lihas_become | default(no) }}"
- name: "Apache2: enable site {{ item }}"
  ansible.builtin.command: a2ensite {{ item }}
  notify: Reload apache2
  changed_when: true
  when: not statresult.stat.exists
  become: "{{ lihas_become | default(no) }}"
