---
- name: "{{ 'Check if ' + item + ' is enabled' }}"
  ansible.builtin.stat:
    path: "{{ '/etc/apache2/mods-enabled/' + item + '.load' }}"
  register: statresult
  become: "{{ lihas_become | default(no) }}"
- name: "Apache2: enable module {{ item }}"
  ansible.builtin.command: a2enmod {{ item }}
  notify: Restart apache2
  changed_when: true
  when: not statresult.stat.exists
  become: "{{ lihas_become | default(no) }}"
