---
- name: Apache enable site
  ansible.builtin.include_tasks: "50-apache-a2ensite.yml"
  loop: apache_sites_enabled
  loop_control:
    loop_var: item
  become: "{{ lihas_become | default(no) }}"
- name: Dummy Zertifikate
  ansible.builtin.include_tasks: "50-apache-dummycert.yml"
  loop: "{{ apache_sites_enabled }}"
  loop_control:
    loop_var: item
  become: "{{ lihas_become | default(no) }}"
