---
# Use from other roles to only enable some modules
- name: apache enable modules
  ansible.builtin.include_tasks: "50-apache-a2enmod.yml"
  loop: apache_modules_enabled
  loop_control:
    loop_var: item
  become: "{{ lihas_become | default(no) }}"
